spring.application.name=LeilaSalaoApi
spring.config.import=optional:file:./env.properties
server.port=${SPRING_SERVER_PORT}
server.servlet.context-path=/api/v1

jwt.public.key=file:out/keys-rsa-jwt/app.pub
jwt.private.key=file:out/keys-rsa-jwt/app.key

spring.profiles.active=${SPRING_PROFILE}

leila.admin.email=${ADMIN_EMAIL}
leila.admin.password=${ADMIN_PASSWORD}

#app.secure-cookies=true

# HIKARI configurado para pequenos monoliticos
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
