spring.application.name=LeilaSalaoApi
#spring.config.import=optional:file:./env.properties
#server.port=${SPRING_SERVER_PORT}
server.port=8080
server.servlet.context-path=/api/v1

#jwt.public.key=classpath:key/app.pub
#jwt.private.key=classpath:key/app.key

#spring.profiles.active=${SPRING_PROFILE}

spring.profiles.active=h2

#app.secure-cookies=true

#spring.jpa.defer-datasource-initialization=true
#spring.sql.init.mode=always

# HIKARI configurado para pequenos monoliticos
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.connection-timeout=15000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.max-lifetime=1200000
